# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQrLZVBkEDTd7xJMNQdJYpFdQoFHc84w
"""

!pip install selenium

import selenium

print(selenium.__version__)

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

!apt-get update -qq
!apt-get install -y chromium-chromedriver -qq
!pip install -q selenium

!pip install -q selenium
!apt-get update -qq
!apt-get install -y chromium -qq

!pip install selenium

!pip install -q selenium
!apt-get update -qq
!apt-get install -y chromium-chromedriver chromium -qq

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service # Import Service

options = Options()
options.add_argument("--headless=new")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-gpu")

options.binary_location = "/usr/bin/chromium"

service = Service(executable_path="/usr/lib/chromium-browser/chromedriver")
driver = webdriver.Chrome(service=service, options=options)

print("Chrome started successfully!")
.

driver.get("https://the-internet.herokuapp.com/dynamic_loading/1")

print(driver.title)
