# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rS580T1zH9wAsuSmhYRMdP-4Xs2e9xF2
"""

!pip install beautifulsoup4

from bs4 import BeautifulSoup

html = """
<div class="product">
    <h2 class="title">Laptop</h2>
    <p class="category">Electronics</p>
    <span class="price">$500</span>
</div>

<div class="product">
    <h2 class="title">Chair</h2>
    <p class="category">Furniture</p>
    <span class="price">$100</span>
</div>
<div class="product">
    <h2 class="title">Phone</h2>
    <p class="category">Electronics</p>
    <span class="price">$300</span>
</div>
"""

soup = BeautifulSoup(html, "html.parser")

products = soup.select(".product")

print(len(products))

for product in products:

    title = product.select_one(".title").get_text(strip=True)
    category = product.select_one(".category").get_text(strip=True)
    price = product.select_one(".price").get_text(strip=True)

    print(title)
    print(category)
    print(price)
    print("---")

import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"

response = requests.get(url)

print(response.status_code)

html = response.text

print(html[:500])

soup = BeautifulSoup(response.text, "html.parser")

import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"

response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

quotes = soup.select(".quote")

print(len(quotes))

for quote in quotes:
    text = quote.select_one(".text").get_text(strip=True)
    author = quote.select_one(".author").get_text(strip=True)

    print(text)
    print(author)
    print("---")

import requests
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

quotes_data = []

quotes = soup.select(".quote")

for quote in quotes:
    text = quote.select_one(".text").get_text(strip=True)
    author = quote.select_one(".author").get_text(strip=True)

    quotes_data.append({
        "quote": text,
        "author": author
    })

print(quotes_data)

import pandas as pd

df = pd.DataFrame(quotes_data)

print(df)

df.to_csv("quotes.csv", index=False)

import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

books = soup.select("article.product_pod")

print("Books on page:", len(books))

book = books[0]

print(book.get_text(" ", strip=True))

category = soup.select("ul.breadcrumb li a")[-1].get_text(strip=True)

print(category)

from dataclasses import dataclass

@dataclass
class Book:
    title: str
    price: float
    category: str
    url: str

from dataclasses import dataclass
from urllib.parse import urljoin

@dataclass
class Book:
    title: str
    price: float
    category: str
    url: str


def extract_books(html, page_url):
    soup = BeautifulSoup(html, "html.parser")

    category = soup.select("ul.breadcrumb li a")[-1].get_text(strip=True)

    books = []

    for book in soup.select("article.product_pod"):

        title = book.select_one("h3 a")["title"]

        price_text = book.select_one(".price_color").get_text(strip=True)

        # Keep only the numeric part
        price = float(
            price_text.replace("£", "").replace("Â", "").strip()
        )

        relative_url = book.select_one("h3 a")["href"]
        book_url = urljoin(page_url, relative_url)

        books.append(
            Book(
                title=title,
                price=price,
                category=category,
                url=book_url
            )
        )

    return books

url = "https://books.toscrape.com/"

response = requests.get(url)

books = extract_books(response.text, url)

print("Books extracted:", len(books))
print(books[0])

from urllib.parse import urljoin

BASE_URL = "https://books.toscrape.com/"

page_urls = []

for page in range(1, 51):
    if page == 1:
        url = BASE_URL
    else:
        url = urljoin(BASE_URL, f"catalogue/page-{page}.html")

    page_urls.append(url)

print("Total pages:", len(page_urls))
print(page_urls[:3])
print(page_urls[-1])

import asyncio
import httpx

SEM = asyncio.Semaphore(10)

async def fetch_page(client, url):
    async with SEM:
        response = await client.get(url, timeout=20)

        response.raise_for_status()

        return url, response.text

async def fetch_all_pages(urls):

    async with httpx.AsyncClient(
        headers={"User-Agent": "Mozilla/5.0"}
    ) as client:

        tasks = [
            fetch_page(client, url)
            for url in urls
        ]

        results = await asyncio.gather(*tasks)

    return results

page_results = await fetch_all_pages(page_urls)

print("Pages downloaded:", len(page_results))

all_books = []

for page_url, html in page_results:
    books = extract_books(html, page_url)
    all_books.extend(books)

print("Total books:", len(all_books))

import pandas as pd

df = pd.DataFrame(all_books)

print(df.head())
print("\nShape:", df.shape)

df.to_csv("books.csv", index=False)

print("books.csv saved successfully!")

category_average = (
    df.groupby("category")["price"]
      .mean()
      .sort_values(ascending=False)
)

print(category_average)

print("Books:", len(df))
print("Columns:", list(df.columns))
print("\nAverage price by category:")
print(category_average)
